[target.'cfg(target_env = "musl")']
# Because the `cross` Docker container sets `CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER`, the
# `linker` key does not work in this file, so we use `rustflags` instead.
# NOTE: This means that any custom `RUSTFLAGS` variable must include this value!
#linker = "./wrap-ld.sh"
rustflags = "-Clinker=./wrap-ld.sh"

# NOTE: On AArch64, the `cross` Docker image sets both `RUSTFLAGS` and
# `CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER`, so we cannot easily do the same thing here.

# x86_64-specific libstdc++ search path. When building for musl, Cargo will merge this with the
# `rustflags` key above.
[target.'cfg(target_arch = "x86_64")']
rustflags = "-Lnative=/usr/local/x86_64-linux-musl/lib"
